version: "3.8"
services:
  db-mysql:
    image: mysql:5.7.40
    restart: always
    environment:
      - MYSQL_DATABASE=truongdev
      - MYSQL_ROOT_PASSWORD=truongdzai
    ports:
      - "3307:3306"
